name: docker-build

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      -
        name: Build image
        run: docker build -t refruity/error-notifier .
      -
        name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: docker-build-finished